### PR TITLE
Planeswalker can now be retrieved correctly

### PR DESCRIPTION
**Pull request by sharpner**
Loyalty was previously the wrong datatype

### CODE REVIEW

**Comment by boombuler** [comment]
Any Idea why the test fails?

**Comment by boombuler** [comment]
I'm merging this PR, because it doesn't break the build. Instead something seems to have broken the travis config. Because the master branch will not build either.

**Comment by sharpner** [comment]
thx locally the tests ran fine

**Comment by boombuler** [comment]
Same here...

Nino <notifications@github.com> schrieb am Mi., 19. Apr. 2017, 21:23:

**Comment by sharpner** [comment]
I looked into this and in my fork I used this travis.yml:
```
language: go
sudo: false
go:
  - 1.8
  - 1.7
script:
  - go test
```

So my guess would be a problem with tip of go.

Had to remove coveralls since I didn't wanna set it up for the fork, but it's possible that the wrapper script could also be the problem. 

hope it helps.

**Comment by boombuler** [comment]
Thanks works fine!

**Comment by sharpner** [comment]
cool :)

**Pull request merged**
